[build]
  # Build command to create the static frontend
  command = "./build.sh"
  
  # Directory to publish (where the built frontend files will be)
  publish = "dist/public"
  
  # Functions directory (not used for this static deployment)
  functions = "netlify/functions"

[build.environment]
  # Node version for the build process
  NODE_VERSION = "20"

# Redirect rules for single-page application
[[redirects]]
  # Catch all routes and serve index.html for client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"